# Generated by Django 3.2.7 on 2021-09-27 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('type', models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff'), ('employee', 'Employee')], default='employee', max_length=255, verbose_name='type')),
                ('country', models.CharField(choices=[('bahrain', 'Bahrain'), ('erbil', 'Erbil'), ('dubai', 'Dubai'), ('iraq', 'Iraq')], max_length=128, verbose_name='country')),
                ('remember_token', models.CharField(blank=True, max_length=100, null=True, verbose_name='remember token')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date joined')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='last update')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('email_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='email verified at')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'users',
            },
        ),
    ]
